### ISSUE TITLE
Fix bindings at "GoalsTable"

### ISSUE THREAD

**Issue by Coriolanuss** [elluvium/Foxy#28]
While populating "GoalsTable" in "NewBusinessSystem" window multiple columns are created. Please help fix bindings.
See method `ImportButton_Click()`
![image](https://cloud.githubusercontent.com/assets/6977530/23303977/030a7a4a-faa0-11e6-82eb-20140f5135f8.png)

**Comment by elluvium** [comment]
Can you send your .xlsx file?

**Comment by Coriolanuss** [comment]
Done. See [Data/Goals.xlsx](https://github.com/elluvium/Foxy/commit/2bb5696b0ab8503efd56cd42c60802710c29491f)
